name: .NET 8 CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET 8 SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore --configuration Release

    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Optional: publish artifact
    - name: Publish
      run: dotnet publish -c Release -o ./publish

    # Optional: Upload artifact
    - name: Upload Published Files
      uses: actions/upload-artifact@v3
      with:
        name: published-app
        path: ./publish
